"""Added indexes

Revision ID: 3065807e9352
Revises: 43e364268ae0
Create Date: 2016-11-07 09:18:33.416986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3065807e9352'
down_revision = '43e364268ae0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_date'), 'document', ['date'], unique=False)
    ### end Alembic commands ###

    #op.execute('CREATE EXTENSION pg_trgm') (run this as superuser)
    op.execute('CREATE INDEX ix_document_id ON document USING gin (id gin_trgm_ops)')
    op.execute('CREATE INDEX ix_document_case ON document USING gin ("case" gin_trgm_ops)')
    op.execute('CREATE INDEX ix_document_case_name ON document USING gin (case_name gin_trgm_ops)')
    op.execute('CREATE INDEX ix_document_tags ON document USING gin (tags gin_trgm_ops)')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_date'), table_name='document')
    ### end Alembic commands ###

    op.execute('DROP INDEX ix_document_id')
    op.execute('DROP INDEX ix_document_case')
    op.execute('DROP INDEX ix_document_case_name')
    op.execute('DROP INDEX ix_document_tags')
    op.execute('DROP EXTENSION pg_trgm')
