"""Added violations column.

Revision ID: 34d58692071b
Revises: 57f4ec7ef7f8
Create Date: 2016-11-16 16:00:35.509630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d58692071b'
down_revision = '57f4ec7ef7f8'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('nonviolations', sa.String(), nullable=True))
    op.add_column('document', sa.Column('violations', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'violations')
    op.drop_column('document', 'nonviolations')
    ### end Alembic commands ###
