"""Removed case model

Revision ID: 43e364268ae0
Revises: 8e24a42f8844
Create Date: 2016-11-07 09:16:06.128945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e364268ae0'
down_revision = '8e24a42f8844'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='case_pkey')
    )
    ### end Alembic commands ###
