"""Added references table

Revision ID: 57f4ec7ef7f8
Revises: 3065807e9352
Create Date: 2016-11-09 10:37:14.954277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f4ec7ef7f8'
down_revision = '3065807e9352'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_references',
    sa.Column('from_id', sa.String(), nullable=False),
    sa.Column('to_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['document.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_references')
    ### end Alembic commands ###
