"""Added tag field to Document.

Revision ID: 8e24a42f8844
Revises: 5dd631175f1c
Create Date: 2016-11-04 16:03:11.684102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e24a42f8844'
down_revision = '5dd631175f1c'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('tags', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'tags')
    ### end Alembic commands ###
